name: install
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/install.yml"
      - "install.sh"
  pull_request:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          git clone https://github.com/Willie169/termux-android-sdk-ndk.git
          cd termux-android-sdk-ndk
          sed -Ei 's|(#!/data/data/com\.termux/files/usr/bin/bash)|\1\nset -euxo pipefail|' install.sh
      - name: Run install.sh
        timeout-minutes: 360
        run: |
          docker run --rm -v "$HOME/termux-android-sdk-ndk:/data/data/com.termux/files/home/termux-android-sdk-ndk" -w "/data/data/com.termux/files/home/termux-android-sdk-ndk" --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            ./install.sh "platform-tools"
          '
